version: '3'
services:
  app1:
    build: ./unet
    environment:
      SCALE: 10
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    environment:
      SCALE: 10
    depends_on:
      - app1
    